UN-OCHA/ocha-api-site

docker/99-elastic-apm-custom.ini
docker/Dockerfile

feat: Install the Elastic APM module with templated config.

---

.env
config/packages/api_platform.yaml
config/packages/web_profiler.yaml

So we can turn them off on production.
See https://github.com/UN-OCHA/tools-ansible/pull/989
Refs: OHA-3

feat: Use env variable to control the animated spider and the profiler.

---

composer.json
composer.lock
symfony.lock

The mailers are configured via ansible. So we now have:
* dev: mailer_dsn: 'smtp://10.10.0.101:25?encryption=&auth_mode='
* prod: mailer_dsn: 'ses+smtp://{{ mailer_username }}:{{ mailer_password }}@default?region=us-east-1'
Refs: OPS-8817

feat: Drop in the AWS SES mailer package, so production can send mail via SES.

---

docker/Dockerfile
docker/etc/nginx/custom/headers.conf
docker/etc/nginx/custom/hsts.conf

The only one I'm not sure about is the CSP. I went with what seems to work just fine on Sesame.
Refs: OHA-23

fix: If nelmio will not handle this in Symfony, just set headers in nginx.

---

docker/Dockerfile
docker/etc/nginx/map_block_http_methods.conf

Which we need for the API.
Refs: OHA-31

feat: Override the nginx methods allow-list file to permit PUT requests.

---

.gitignore
migrations/Version20230216120620.php
src/Entity/KeyFigures.php
src/Serializer/KeyFigureSerializer.php
tests/KeyFiguresSrc3StringBatchTest.php
tests/KeyFiguresSrc3StringTest.php

feat: allow string data

---

composer.lock

Refs: OPS-8549 and https://humanitarian.atlassian.net/browse/OPS-8835
This should be done more regularly in the future. The changes are from running `composer update -W` - seems to be working fine, the phpunit tests are all passing, but I'm not familiar with the site yet so might need some more testing.

chore: composer updates

---

README.md
templates/home.html.twig

chore: Correct docs

---

CHANGELOG.md
migrations/Version20230516083216.php
src/Entity/KeyFigures.php
src/Entity/User.php
src/Serializer/KeyFigureSerializer.php
src/State/User/MeProvidersStateProvider.php
templates/home.html.twig

feat: Add endpoint to get providers

---

config/packages/monolog.yaml

Am much guessing at the syntax.
Refs: OPS-9323

chore: Make prod log to file, not stderr, so the file can go into ELK.

---

migrations/Version20230621094308.php
migrations/Version20230621094646.php
src/Entity/Country.php
src/Entity/OchaPresence.php
src/Serializer/KeyFigureSerializer.php

bug: data overwritten

---

composer.json
composer.lock
config/bundles.php
config/packages/sensio_framework_extra.yaml
symfony.lock

Refs: OPS-9395
Compose update and removing deprecated package as advised by composer.

chore: update packages and remove deprecated package

---

composer.json
composer.lock
config/bundles.php
config/packages/doctrine.yaml
config/packages/netbrothers_version.yaml
migrations/Version20231026105300.php
src/Entity/Country.php
src/Entity/ExternalLookup.php
src/Entity/OchaPresence.php
src/Entity/OchaPresenceExternalId.php
symfony.lock

feat: Add versioning to Ocha Presences

---

config/packages/api_platform.yaml
templates/home.html.twig

feat: Add beta info

---

docker/etc/nginx/custom/headers.conf

bug: csp worker-src

---

docker/Dockerfile
src/Entity/KeyFigures.php
tests/KeyFiguresSrc3BatchTest.php
tests/OchaPresenceExternalIdTest.php

bug: missing default value

---

.github/workflows/docker-build-image.yml
.github/workflows/run-tests.yml

chore: bump github action versions

---

templates/home.html.twig

feat: Remove reference to RW crisis figures

---

composer.lock
docker/Dockerfile
docker/etc/nginx/custom/headers.conf
templates/home.html.twig

Deploy 16-04-2024

---

docker/Dockerfile

chore: remove last reference to apm-agent

---

.github/workflows/run-tests.yml

chore: use docker compose v2 for tests

---

tests/docker-compose.yml

tests: Bump the MariaDB in tests to 11.4.

---

docker/Dockerfile

And see if everything keeps working.
Refs: OPS-11599

chore(security): Bump API to PHP 8.3
